spring:
  # 数据库连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reggie
    username: root
    password: 123456
  # 文件上传的配置
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  application:
    # 应用名称
    name: reggie

# mybatis配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 将驼峰命名与下划线命名相互转换
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*xml
  type-aliases-package: com.niepan.pojo
# 阿里云OSS
#aliyun:
#  oss:
#    endpoint: https://oss-cn-beijing.aliyuncs.com
#    accessKeyId: LTAI5t9kHwZCcPDsMoykQAPu
#    accessKeySecret: AXXAvZriCjyEAKk43hQLdwFU47eXos
#    bucketName: zzx-talis

# 服务器配置
server:
  port: 8080

# spring事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
#应用名称name